# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Renato Fialho
tagline:             'Renato Fialho Blog'
description:         'Renato Fialho Blog'
url:                 www.renatofialho.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Renato Fialho
  url:               https://github.com/fialhorenato
  email:             renato@renatofialho.com

# Custom vars
version:             1.0.0
