title:            Blog - Renato Fialho
description:      Blog - Renato Fialho
disqus_shortname: shortname
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:              //fialhorenato.github.io

# Owner/author information
owner:
  name:           Renato Fialho
  avatar:         avatar.jpg
  bio:            “O sol nasce, a bicicleta anda, o lobo uiva e o urso panda."
  email:          renato@renatofialho.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        renatobh
  facebook:       fialho.renato
  github:         fialhorenato
  stackexchange:
  linkedin:
  instagram:      renatofialho
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +renatofialho

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5
