

# Setup
title:               Renato Fialho
tagline:             'Blog'
description:         'Blog'
url:                 www.renatofialho.com
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Renato Fialho
  url:               https://github.com/fialhorenato
  email:             renato@renatofialho.com

# Custom vars
version:             1.0.0
