baseURL = "http://renatofialho.com/"
title = "Renato Fialho"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pygmentsstyle = "bw"

googleAnalytics = "UA-35245135-2"

[blackfriday]
    hrefTargetBlank = true

[params]
    author = "Renato Fialho"
    info = "Software Engineer"
    description = "Renato Fialho's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"


    hidecredits = false
    hidecopyright = false

    rtl = false

    math = false
    custom_css = ["css/custom.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/fialhorenato/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/renatobh/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 3
    url = "/contact/"